server:
  port: 1996
eureka:
  client:
    serviceUrl:
      defaultZone: http://172.0.0.1:1996/eureka/
  instance:
    prefer-ip-address: true
spring:
  application:
    name: ZUUL-PARENT
zuul:
  routes:
    aigou_plat: /login/**
  ignored-services: "*"
  prefix: /aigou
